BEGIN;

DROP TABLE IF EXISTS "movie", "type", "director", "list", "movie_type", "movie_director", "movie_list";

CREATE TABLE "movie" (
  "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(255) NOT NULL UNIQUE,
  "date" INTEGER NOT NULL,
  "resume" TEXT NOT NULL,
  "image" VARCHAR(255) NOT NULL,
  "bande_annonce" VARCHAR(255)  
);

CREATE TABLE "type" (
  "id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(255) NOT NULL
);

CREATE TABLE "director" (
  "id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(255) NOT NULL
);

CREATE TABLE "list" (
  "id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(255) NOT NULL
);

CREATE TABLE "movie_type" (
  "id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "movie_id" int NOT NULL REFERENCES "movie"("id"),
  "type_id" int NOT NULL REFERENCES "type"("id")
);

CREATE TABLE "movie_director" (
  "id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "movie_id" int NOT NULL REFERENCES "movie"("id"),
  "director_id" int NOT NULL REFERENCES "director"("id")
);

CREATE TABLE "movie_list" (
  "id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "movie_id" int NOT NULL REFERENCES "movie"("id"),
  "list_id" int NOT NULL REFERENCES "list"("id")
);

COMMIT;